version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  plugin-ci:
    jobs:
      - orb-tools/publish:
          context: matterbuild-circleci-token
          orb-path: plugin-ci/orb.yml
          orb-ref: mattermost/plugin-ci@dev:${CIRCLE_BRANCH}
          publish-token-variable: "$CIRCLECI_TOKEN"
          validate: true
          filters:
            branches:
              ignore:
                - master
      - approve-increment:
          type: approval
          filters:
            branches:
              only: master
      - orb-tools/increment:
          context: matterbuild-circleci-token
          orb-path: plugin-ci/orb.yml
          orb-ref: "mattermost/plugin-ci"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_TOKEN"
          filters:
            branches:
              only:
                - master
          requires: [approve-increment]
      - orb-tools/publish:
          context: matterbuild-circleci-token
          orb-path: plugin-ci/orb.yml
          orb-ref: "mattermost/plugin-ci"
          publish-token-variable: "$CIRCLECI_TOKEN"
          validate: true
          requires: [orb-tools/increment]
          filters:
            branches:
              only:
                - master
