version: 2.1

orb_prep_jobs: &orb_prep_jobs
  [
    orb-tools/lint,
    orb-tools/shellcheck,
    orb-tools/pack
  ]

orbs:
  orb-tools: circleci/orb-tools@9.2
  plugin-ci: mattermost/plugin-ci@<<pipeline.parameters.dev-orb-version>>

parameters:
  dev-orb-version:
    type: string
    default: "dev:alpha"

workflows:
  plugin-ci_lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint:
          lint-dir: plugin-ci
      - orb-tools/shellcheck:
          source-dir: plugin-ci
      - orb-tools/pack:
          source-dir: plugin-ci
      - orb-tools/publish-dev:
          context: matterbuild-circleci-token
          publish-token-variable: METANERD_ORB_PUBLISHER
          orb-name: mattermost/plugin-ci
          requires: *orb_prep_jobs

  # publish semver by setting commit subject text "[semver:patch|minor|major|skip]"
  # e.g. git commit -am "[semver:patch] Final final fix version 2".
  plugin-ci_orb-publishing:
    jobs:
      - orb-tools/publish-dev: # Republish dev orb so that the promotion step finds the published dev orb commit due to squashing
          context: matterbuild-circleci-token
          publish-token-variable: METANERD_ORB_PUBLISHER
          orb-name: mattermost/plugin-ci
      - orb-tools/dev-promote-prod-from-commit-subject:
          context: matterbuild-circleci-token
          publish-token-variable: METANERD_ORB_PUBLISHER
          orb-name: mattermost/plugin-ci
          add-pr-comment: false
          publish-version-tag: false
          fail-if-semver-not-indicated: false
          requires: [ orb-tools/publish-dev ]
          filters:
            branches:
              only: master
